# Place this file next to the streama-[version].war on deployment
environments:
    production:
        dataSource:
            driverClassName:  'org.h2.Driver'
            url: jdbc:h2:./data/streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: root
            password:
        server:
            port: 8080
